# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ed5326a86768f9b3714308c8cd130f766256e6413a2574408449e63c7fddc0f4dccc6dbd174faa53c43c2a1f6a389d8e07e991ce71b4102a764f8435c56d63

test:
  secret_key_base: 19cf068b7b1dc8a718168342da98c9e7c0fe13e76c908622d53d4893069d14d5e446492cde9788f182560abeef699c131ae93730acb85b41c68c5710c6a365a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
